CREATE TABLE branch ( id INTEGER NOT NULL, name VARCHAR(50) UNICODE NOT NULL, last_user_id INTEGER NULL, PRIMARY KEY (id))
CREATE TABLE language ( id INTEGER NOT NULL , name VARCHAR(30) UNICODE NOT NULL, PRIMARY KEY (id))
CREATE TABLE user_types( id INTEGER NOT NULL, name VARCHAR(25) UNICODE NOT NULL, titles_no INTEGER NOT NULL, period VARCHAR(8) UNICODE, PRIMARY KEY (id))
CREATE TABLE users( id VARCHAR(11) NOT NULL, city VARCHAR(45) UNICODE NULL, zipcode INTEGER NULL, address VARCHAR(150) UNICODE NULL, sign_date DATE NULL, warning NUMBER(1) NULL, phone VARCHAR(50) UNICODE NULL, email VARCHAR(50) UNICODE NULL, user_type INTEGER NOT NULL, branch_id INTEGER NULL, branch_card VARCHAR(20) UNICODE NULL, branch_sign_date DATE NULL, PRIMARY KEY (id), FOREIGN KEY (user_type) REFERENCES USER_TYPES (id), FOREIGN KEY (branch_id) REFERENCES BRANCH (id))
CREATE TABLE edu_lvl( id INTEGER NOT NULL, name VARCHAR(30) UNICODE NOT NULL, PRIMARY KEY (id))
CREATE TABLE user_categs( id INTEGER NOT NULL, name VARCHAR(100) UNICODE NOT NULL, titles_no INTEGER NOT NULL, period VARCHAR(8) UNICODE NULL, PRIMARY KEY (id))
CREATE TABLE mmbr_types( id INTEGER NOT NULL, name VARCHAR(100) UNICODE NOT NULL, titles_no INTEGER NOT NULL, period VARCHAR(8) UNICODE NULL, PRIMARY KEY (id) )
CREATE TABLE duplicate (user_id VARCHAR(11) NOT NULL, dup_no INTEGER NOT NULL, dup_date DATE, PRIMARY KEY (user_id, dup_no), FOREIGN KEY (user_id) REFERENCES USERS (id))
CREATE TABLE block_reasons (id INTEGER NOT NULL , name VARCHAR(30) UNICODE NOT NULL, PRIMARY KEY (id))
CREATE TABLE blocked_cards (user_id VARCHAR(11) NOT NULL, reason_id INTEGER NOT NULL, note VARCHAR(150) UNICODE NULL, PRIMARY KEY (user_id, reason_id), FOREIGN KEY (user_id) REFERENCES USERS (id), FOREIGN KEY (reason_id) REFERENCES BLOCK_REASONS (id))
CREATE TABLE groups( inst_name VARCHAR(45) UNICODE NOT NULL, sec_address VARCHAR(45) UNICODE NULL, sec_city VARCHAR(30) UNICODE NULL, sec_zip INTEGER NULL, sec_phone VARCHAR(30) UNICODE NULL, fax VARCHAR(15) UNICODE NULL, telex VARCHAR(15) UNICODE NULL, cont_fname VARCHAR(30) UNICODE NULL, cont_lname VARCHAR(30) UNICODE NULL, cont_email VARCHAR(30) UNICODE NULL, user_id VARCHAR(11) NOT NULL, PRIMARY KEY (user_id), FOREIGN KEY (user_id) REFERENCES USERS (id) )
CREATE TABLE single( dob DATE NULL, first_name VARCHAR(30) UNICODE NULL, permission NUMBER(1) NULL, last_name VARCHAR(30) UNICODE NULL, occupation VARCHAR(30) UNICODE NULL, country VARCHAR(30) UNICODE NULL, password VARCHAR(8) UNICODE NULL, passport VARCHAR(15) UNICODE NULL, organization VARCHAR(150) UNICODE NULL, org_address VARCHAR(150) UNICODE NULL, org_city VARCHAR(30) UNICODE NULL, org_zip INTEGER NULL, org_phone VARCHAR(30) UNICODE NULL, temp_addr VARCHAR(150) UNICODE NULL, temp_city VARCHAR(50) UNICODE NULL, temp_zip INTEGER NULL, temp_phone VARCHAR(15) UNICODE NULL, index_no VARCHAR(15) UNICODE NULL, jmbg CHAR(13) NULL, edu_lvl INTEGER NULL, user_ctgr INTEGER NOT NULL, mmbr_type INTEGER NOT NULL, grp_id VARCHAR(11) NULL, user_id VARCHAR(11) NOT NULL, parent_name VARCHAR(30) UNICODE, doc_id integer, doc_no VARCHAR(15) UNICODE, doc_city VARCHAR(30) UNICODE, title VARCHAR(30) UNICODE, note VARCHAR(200) UNICODE, interests VARCHAR(60) UNICODE, gender integer, language INTEGER NULL, age INTEGER NULL, PRIMARY KEY (user_id), FOREIGN KEY (edu_lvl) REFERENCES EDU_LVL (id), FOREIGN KEY (user_ctgr) REFERENCES USER_CATEGS (id), FOREIGN KEY (mmbr_type) REFERENCES MMBR_TYPES (id), FOREIGN KEY (grp_id) REFERENCES GROUPS (user_id), FOREIGN KEY (user_id) REFERENCES USERS (id), FOREIGN KEY (language) REFERENCES LANGUAGE (id))
CREATE TABLE institutions( inst_name VARCHAR(45) UNICODE NOT NULL, cont_fname VARCHAR(30) UNICODE NOT NULL, cont_lname VARCHAR(30) UNICODE NOT NULL, cont_email VARCHAR(30) UNICODE NULL, cont_phone VARCHAR(15) UNICODE NULL, sec_phone VARCHAR(15) UNICODE NULL, fax VARCHAR(15) UNICODE NULL, telex VARCHAR(15) UNICODE NULL, user_id VARCHAR(11) NOT NULL, PRIMARY KEY (user_id), FOREIGN KEY (user_id) REFERENCES USERS (id) )
CREATE TABLE slikovnice( user_id VARCHAR(11) NOT NULL, datum DATE NOT NULL, izdato INTEGER NULL, vraceno INTEGER NULL, stanje INTEGER NULL, bib_id CHAR(50) UNICODE NOT NULL, PRIMARY KEY (user_id, datum), FOREIGN KEY (user_id) REFERENCES SINGLE (user_id))
CREATE TABLE membership( user_ctgr INTEGER NOT NULL, mmbr_type INTEGER NOT NULL, mdate DATE NOT NULL, cost NUMBER(8,2) NULL, hard_curr NUMBER(8,2) NULL, PRIMARY KEY (mdate, user_ctgr, mmbr_type), FOREIGN KEY (user_ctgr) REFERENCES USER_CATEGS (id), FOREIGN KEY (mmbr_type) REFERENCES MMBR_TYPES (id))
CREATE TABLE signing( single_id VARCHAR(11) NOT NULL, bib_id CHAR(50) UNICODE NOT NULL, sdate DATE NOT NULL, cost NUMBER(8,2) NULL, hard_curr NUMBER(8,2) NULL, receipt_id VARCHAR(30) UNICODE NULL, until_date DATE NULL, PRIMARY KEY (sdate, bib_id, single_id), FOREIGN KEY (single_id) REFERENCES SINGLE (user_id))
CREATE TABLE officials( id INTEGER NOT NULL, last_name VARCHAR(30) UNICODE NOT NULL, first_name VARCHAR(15) UNICODE NOT NULL, email VARCHAR(45) UNICODE NULL, PRIMARY KEY (id))
CREATE TABLE location( id INTEGER NOT NULL, name VARCHAR(100) UNICODE NOT NULL, PRIMARY KEY (id))
CREATE TABLE lend_types( id INTEGER NOT NULL, name VARCHAR(45) UNICODE NOT NULL, titles_no INTEGER NOT NULL, period VARCHAR(8) UNICODE NULL, PRIMARY KEY (id))
CREATE TABLE lending( ctlg_no VARCHAR(30) UNICODE NOT NULL, single_id VARCHAR(11) NOT NULL, lend_date DATE NOT NULL, return_date DATE NULL, resume_date DATE NULL, bib_id CHAR(50) UNICODE NOT NULL, lend_type INTEGER NOT NULL, location INTEGER NOT NULL, description VARCHAR(30) UNICODE NULL, counter INTEGER NOT NULL, PRIMARY KEY (lend_date, single_id, ctlg_no, counter), FOREIGN KEY (single_id) REFERENCES SINGLE (user_id), FOREIGN KEY (lend_type) REFERENCES LEND_TYPES (id), FOREIGN KEY (location) REFERENCES LOCATION (id))
CREATE TABLE circ_docs( sig VARCHAR(255) UNICODE NULL, ctlg_no VARCHAR(255) UNICODE NOT NULL, docid NUMBER(38) NOT NULL, status INTEGER NOT NULL, rcv_req_id INTEGER, type VARCHAR(10) UNICODE NULL, state CHAR(15) UNICODE NULL, PRIMARY KEY (ctlg_no) )
CREATE TABLE reservations( single_id VARCHAR(11) NOT NULL, ctlg_no VARCHAR(30) UNICODE NOT NULL, rsrv_date DATE NOT NULL, notification NUMBER(1) NOT NULL, resume_date DATE NULL, bib_id CHAR(50) UNICODE NOT NULL, PRIMARY KEY (rsrv_date, ctlg_no, single_id), FOREIGN KEY (single_id) REFERENCES SINGLE (user_id))
CREATE TABLE publications_reservations( ctlg_no VARCHAR(30) UNICODE NOT NULL, rsrv_date DATE NOT NULL, single_id VARCHAR(11) NOT NULL, pub_ctlg_no VARCHAR(30) UNICODE NOT NULL, PRIMARY KEY (ctlg_no, rsrv_date, single_id, pub_ctlg_no), FOREIGN KEY (rsrv_date, pub_ctlg_no, single_id) REFERENCES RESERVATIONS ( rsrv_date, ctlg_no, single_id))
CREATE TABLE self_rsrv( single_id VARCHAR(11) NOT NULL, ctlg_no VARCHAR(30) UNICODE NOT NULL, rsrv_date DATE NOT NULL, notification NUMBER(1) NOT NULL, resume_date DATE NULL, PRIMARY KEY (rsrv_date, ctlg_no, single_id), FOREIGN KEY (single_id) REFERENCES SINGLE (user_id))
CREATE TABLE lend_brw( id INTEGER NOT NULL, author VARCHAR(60) UNICODE NOT NULL, payment VARCHAR(15) UNICODE NOT NULL, title VARCHAR(60) UNICODE NOT NULL, cost NUMBER(8,2) NOT NULL, type VARCHAR(15) UNICODE NOT NULL, pieces_no INTEGER NULL, comments VARCHAR(60) UNICODE NULL, hard_curr NUMBER(8,2) NULL, PRIMARY KEY (id))
CREATE TABLE received_req( lendbrw_id INTEGER NOT NULL, accept_date DATE NOT NULL, institution VARCHAR(45) UNICODE NOT NULL, lend_date DATE NULL, return_date DATE NULL, inst_id VARCHAR(11) NOT NULL, PRIMARY KEY (lendbrw_id), FOREIGN KEY (inst_id) REFERENCES INSTITUTIONS (user_id), FOREIGN KEY (lendbrw_id) REFERENCES LEND_BRW(id))
CREATE TABLE sent_req( lendbrw_id INTEGER NOT NULL, send_date DATE NOT NULL, institution VARCHAR(45) UNICODE NOT NULL, accept_date DATE NULL, return_date DATE NULL, inst_id VARCHAR(11) NOT NULL, PRIMARY KEY (lendbrw_id), FOREIGN KEY (inst_id) REFERENCES INSTITUTIONS (user_id), FOREIGN KEY (lendbrw_id) REFERENCES LEND_BRW(id))
CREATE TABLE borrowed_pub( id INTEGER NOT NULL, catalogue_no VARCHAR(30) UNICODE NOT NULL, author VARCHAR(60) UNICODE NOT NULL, title VARCHAR(60) UNICODE NOT NULL, sent_req_id INTEGER NOT NULL, PRIMARY KEY (id), FOREIGN KEY (sent_req_id) REFERENCES SENT_REQ (lendbrw_id))
CREATE TABLE warning_types( id INTEGER NOT NULL, name VARCHAR(50) UNICODE NOT NULL, wtext VARCHAR(3000) UNICODE NOT NULL, PRIMARY KEY (id))
CREATE TABLE warn_counters( warn_type INTEGER NOT NULL, warn_year INTEGER NOT NULL, last_no INTEGER NULL, PRIMARY KEY (warn_type, warn_year), FOREIGN KEY (warn_type) REFERENCES WARNING_TYPES (id))
CREATE TABLE warnings( warn_type INTEGER NOT NULL, user_id VARCHAR(11) NOT NULL, ctlg_no VARCHAR(30) UNICODE NOT NULL, warn_no VARCHAR(20) NULL, wdate DATE NOT NULL, deadline DATE, location INTEGER NULL, return_date DATE NULL, note VARCHAR(100) UNICODE NULL, PRIMARY KEY (warn_type, user_id, ctlg_no, wdate), FOREIGN KEY (warn_type) REFERENCES WARNING_TYPES (id), FOREIGN KEY (user_id) REFERENCES USERS (id), FOREIGN KEY (location) REFERENCES LOCATION (id))
CREATE INDEX USER_USTP_IDX ON USERS(user_type )
CREATE INDEX USER_BRCH_IDX ON USERS(branch_id )
CREATE INDEX SNGL_USCT_IDX ON SINGLE( user_ctgr )
CREATE INDEX SNGL_GRP_IDX ON SINGLE(grp_id )
CREATE INDEX SNGL_EDU_IDX ON SINGLE(edu_lvl )
CREATE INDEX SNGL_MBTP_IDX ON SINGLE(mmbr_type )
CREATE INDEX SNGL_LANG_IDX ON SINGLE(language )
CREATE INDEX SNRQ_INST_IDX ON SENT_REQ(inst_id)
CREATE INDEX BRPB_SNRQ_IDX ON BORROWED_PUB(sent_req_id)
CREATE INDEX PUBL_RSRV_PUBL_IDX ON PUBLICATIONS_RESERVATIONS(ctlg_no )
CREATE INDEX PUB_REZ_REZ_IDX ON PUBLICATIONS_RESERVATIONS( rsrv_date, single_id, pub_ctlg_no )
CREATE INDEX RCRQ_INST_IDX ON RECEIVED_REQ(inst_id)
CREATE INDEX RSRV_SNGL_IDX ON RESERVATIONS(single_id)
CREATE INDEX RSRV_PUBL_IDX ON RESERVATIONS(ctlg_no )
CREATE INDEX SLFR_SNGL_IDX ON SELF_RSRV(single_id )
CREATE INDEX SLFR_PUBL_IDX ON SELF_RSRV(ctlg_no )
CREATE INDEX SIGN_SNGL_IDX ON SIGNING (single_id )
CREATE INDEX MMBR_USCT_IDX ON MEMBERSHIP(user_ctgr)
CREATE INDEX MMBR_MBTP_IDX ON MEMBERSHIP(mmbr_type)
CREATE INDEX LEND_SNGL_IDX ON LENDING(single_id )
CREATE INDEX LEND_PUBL_IDX ON LENDING(ctlg_no )
CREATE INDEX LEND_LNDT_IDX ON LENDING(lend_type ,location )
CREATE INDEX LEND_RTRN_IDX ON LENDING(return_date )
CREATE INDEX LEND_RSUM_IDX ON LENDING(resume_date )
CREATE INDEX WARN_DATE_IDX ON WARNINGS(deadline)
CREATE INDEX WARN_LOCA_IDX ON WARNINGS(location)
CREATE INDEX WARN_WRNO_IDX ON WARNINGS(warn_no)
CREATE INDEX CIRC_DOCS_IDX ON CIRC_DOCS(docid)
CREATE INDEX CIRC_DOCS_2 ON CIRC_DOCS(sig)
CREATE INDEX DUPL_USER_IDX ON DUPLICATE(user_id)
CREATE INDEX BLCK_USER_IDX ON BLOCKED_CARDS(user_id)
INSERT INTO user_types VALUES(1,'Individue',5,10)
INSERT INTO user_types VALUES(2,'Kolektivni',10,15)
INSERT INTO user_types VALUES(3,'Instit Razmene',30,30)
INSERT INTO user_categs VALUES(11,'U^ENICI',5,10)
INSERT INTO user_categs VALUES(12,'STUDENTI DRU[TVENIH NAUKA',10,15)
INSERT INTO user_categs VALUES(13,'STUDENTI PRIRODNIH NAUKA',30,30)
INSERT INTO user_categs VALUES(14,'STUDENTI UMETNOSTI',15,15)
INSERT INTO user_categs  VALUES(15,'RADNICI',15,15)
INSERT INTO user_categs  VALUES(16,'SLU@BENICI',15,15)
INSERT INTO user_categs  VALUES(17,'STRU^NJACI DRU[TVENIH NAUKA',15,15)
INSERT INTO user_categs VALUES(18,'STRU^NJACI PRIRODNIH NAUKA',15,15)
INSERT INTO user_categs VALUES(19,'UMETNI^KE PROFESIJE',15,15)
INSERT INTO user_categs VALUES(20,'PRIVATNI PREDUZETNICI',15,15)
INSERT INTO user_categs VALUES(21,'PENZIONERI',15,15)
INSERT INTO user_categs VALUES(22,'DOMA]ICE',15,15)
INSERT INTO user_categs VALUES(23,'OSTALI',15,15)
INSERT INTO user_categs VALUES(24,'STUDENTI BIBLIOTEKARSTVA',15,15)
INSERT INTO user_categs VALUES(25,'BIBLIOTEKARI',15,15)
INSERT INTO user_categs VALUES(26,'KNJI@NI^ARI',15,15)
INSERT INTO user_categs VALUES(27,'SLU@BENICI BGB',15,15)
INSERT INTO user_categs VALUES(28,'STUDENTI DIF-a',15,15)
INSERT INTO user_categs VALUES(07,'OSTALI',15,15)
INSERT INTO users VALUES (0, 'x', 123, 'x', TRUNC(SYSDATE), 0, NULL, NULL, 1, NULL, NULL, NULL)
INSERT INTO edu_lvl VALUES(99,'x')
INSERT INTO edu_lvl VALUES(0,'NEPOZNATA STRU^NA SPREMA')
INSERT INTO edu_lvl VALUES(1,'I STEPEN - OSNOVNA [KOLA')
INSERT INTO edu_lvl VALUES(2,'II STEPEN - DVOGOD. [KOLA')
INSERT INTO edu_lvl VALUES(3,'III STEPEN - TROGOD.[KOLA')
INSERT INTO edu_lvl VALUES(4,'IV STEPEN - SREDNJA [KOLA')
INSERT INTO edu_lvl VALUES(5,'V STEPEN - VI[A [KOLA')
INSERT INTO edu_lvl VALUES(6,'VI - STEPEN ')
INSERT INTO mmbr_types VALUES(0,'GRE[KA',5,365)
INSERT INTO mmbr_types VALUES(1,'REDOVAN ^LAN',5,365)
INSERT INTO mmbr_types VALUES(2,'PREDUZE]A',5,365)
INSERT INTO mmbr_types VALUES(3,'SAJAM',5,365)
INSERT INTO mmbr_types VALUES(4,'KOLEKTIVNI UPIS',5,365)
INSERT INTO mmbr_types VALUES(5,'NE PLA]A ^LANARINU',5,365)
INSERT INTO mmbr_types VALUES(6,'^LAN.UDR.BIBLIOTEKA',5,365)
INSERT INTO mmbr_types VALUES(7,'STUD.BIBLIOTEKARSTVA',5,365)
INSERT INTO mmbr_types VALUES(8,'ADA CIGANLIJA',5,365)
INSERT INTO mmbr_types VALUES(9,'MATURANTI  02/03',5,365)
INSERT INTO mmbr_types VALUES(10,'EURO < 26; ETC',5,365)
INSERT INTO mmbr_types VALUES(11,'ISIC',5,365)
INSERT INTO mmbr_types VALUES(12,'PORODI^NO ^LANSTVO',5,365)
INSERT INTO mmbr_types VALUES(13,'STUDENTSKI GRAD',5,365)
INSERT INTO lend_types VALUES (1, 'U ~itaonici', 5, 1)
INSERT INTO lend_types VALUES (2, 'Van ~itaonice', 5, 15)
INSERT INTO language VALUES(0,'Srpski jezik - latinica')
INSERT INTO language VALUES(1,'Srpski jezik - }irilica')
INSERT INTO language VALUES(2,'Ma|arski jezik')
INSERT INTO language VALUES(3,'Nema~ki jezik')
INSERT INTO language VALUES(4,'Engleski jezik')
INSERT INTO language VALUES(5,'Ruski jezik')
INSERT INTO language VALUES(6,'Rumunski jezik')
INSERT INTO language VALUES(7,'Slova~ki jezik')
INSERT INTO language VALUES(8,'Francuski jezik')
INSERT INTO language VALUES(9,'Slovena~ki jezik')
INSERT INTO language VALUES(10,'Italijanski jezik')
INSERT INTO language VALUES(11,'Latinski jezik')
INSERT INTO language VALUES(12,'Makedonski jezik')
INSERT INTO language VALUES(13,'Japanski jezik')
INSERT INTO language VALUES(14,'[vedski jezik')
INSERT INTO language VALUES(15,'Romski jezik')
INSERT INTO language VALUES(16,'Rusinski jezik')
INSERT INTO language VALUES(17,'Poljski jezik')
INSERT INTO language VALUES(18,'Gr~ki jezik')
INSERT INTO branch VALUES (000,'Mre`a biblioteka', 0)
INSERT INTO branch VALUES (001,'Biblioteka grada Beograda, Pult', 0)
INSERT INTO branch VALUES (002,'BGB - De~je o. "^ika Jova Zmaj"', 0)
INSERT INTO branch VALUES (003,'BGB - De~je o. "Neven"', 0)
INSERT INTO branch VALUES (004,'BGB - Ameri~ki kutak', 0)
INSERT INTO branch VALUES (100,'Vo`d - B. "Dositej Obradovi}', 0)
INSERT INTO branch VALUES (101,'Vo`d - B. "Dositej Obradovi}", De~je', 0)
INSERT INTO branch VALUES (102,'Vo`d - og. "Milorad Pani} Surep"', 0)
INSERT INTO branch VALUES (103,'Vo`d - og. "Kara|or|e"', 0)
INSERT INTO branch VALUES (104,'Vo`d - og. "Milutin Uskokovi}"', 0)
INSERT INTO branch VALUES (105,'Vo`d - og. "Stepa Stepanovi}"', 0)
INSERT INTO branch VALUES (106,'Vo`d - og. "Filip Vi{nji}"', 0)
INSERT INTO branch VALUES (107,'Vo`d - og. "Milan \. Mili}evi}"', 0)
INSERT INTO branch VALUES (120,'Vra~ - B. "Petar Ko~i}"', 0)
INSERT INTO branch VALUES (121,'Vra~ - B. "Petar Ko~i}", De~je', 0)
INSERT INTO branch VALUES (122,'Vra~ - og. "Borislav Peki}"', 0)
INSERT INTO branch VALUES (123,'Vra~ - og. "Laza Lazarevi}"', 0)
INSERT INTO branch VALUES (124,'Vra~ - og. "Svetozar Markovi}"', 0)
INSERT INTO branch VALUES (140,'Zvez - B. "Vuk Karad`i}"', 0)
INSERT INTO branch VALUES (141,'Zvez - og. "Radoje Domanovi}"', 0)
INSERT INTO branch VALUES (142,'Zvez - og. "Bla`o [}epanovi}"', 0)
INSERT INTO branch VALUES (143,'Zvez - og. "Milorad Pani} Surep"', 0)
INSERT INTO branch VALUES (144,'Zvez - og. "Dragi{a Vito{evi}"', 0)
INSERT INTO branch VALUES (145,'Zvez - og. "Branko Miljkovi}"', 0)
INSERT INTO branch VALUES (146,'Zvez - og. "Jefimija"', 0)
INSERT INTO branch VALUES (160,'^uka - B. "Laza Kosti}"', 0)
INSERT INTO branch VALUES (161,'^uka - og. "Prometej"', 0)
INSERT INTO branch VALUES (162,'^uka - og. "Du{ko Radovi}"', 0)
INSERT INTO branch VALUES (163,'^uka - og. "Branko ]opi}"', 0)
INSERT INTO branch VALUES (164,'^uka - og. "\ura Jak{i}"', 0)
INSERT INTO branch VALUES (165,'^uka - og. "Dimitrije Tucovi}"', 0)
INSERT INTO branch VALUES (166,'^uka - og. "Cerak"', 0)
INSERT INTO branch VALUES (167,'^uka - og. "Ru{anj"', 0)
INSERT INTO branch VALUES (168,'^uka - og. "Ostru`nica"', 0)
INSERT INTO branch VALUES (180,'Rako - B. "Miodrag Bulatovi}"', 0)
INSERT INTO branch VALUES (181,'Rako - og. "Miroslav Anti}"', 0)
INSERT INTO branch VALUES (182,'Rako - og. "Du{an Mati}"', 0)
INSERT INTO branch VALUES (183,'Rako - og. "Ivo Andri}"', 0)
INSERT INTO branch VALUES (184,'Rako - og. "Milo{ Crnjanski"', 0)
INSERT INTO branch VALUES (185,'Rako - og. "Isidora Sekuli}"', 0)
INSERT INTO branch VALUES (200,'Mlad - B. "Despot Stefan Lazarevi}"', 0)
INSERT INTO branch VALUES (201,'Mlad - De~je odeljenje', 0)
INSERT INTO branch VALUES (220,'Bara - B. "Jovan Du~i}"', 0)
INSERT INTO branch VALUES (221,'Bara - og. "Vrani}"', 0)
INSERT INTO branch VALUES (222,'Bara - og. "Banko Radi~evi}", Meljak', 0)
INSERT INTO branch VALUES (240,'Savv - B. "Isidora Sekuli}"', 0)
INSERT INTO branch VALUES (241,'Savv - De~je odeljenje "Vojislav Ili}"', 0)
INSERT INTO branch VALUES (242,'Savv - og. "Jovan Jovanovi} Zmaj"', 0)
INSERT INTO branch VALUES (243,'Savv - og. "Veselin Masle{a"', 0)
INSERT INTO branch VALUES (244,'Savv - og. "Branko Stankovi}"', 0)
INSERT INTO branch VALUES (245,'Savv - og. "Veljko Petrovi}"', 0)
INSERT INTO branch VALUES (246,'Savv - punkt BIP', 0)
INSERT INTO branch VALUES (260,'Stag - B. "\or|e Jovanovi}"', 0)
INSERT INTO branch VALUES (261,'Stag - De~je odeljenje', 0)
INSERT INTO branch VALUES (262,'Stag - og. "Jovan Popovi}"', 0)
INSERT INTO branch VALUES (263,'Stag - punkt "Energogas"', 0)
INSERT INTO branch VALUES (280,'NBgd - B. "Vuk Karad`i}"', 0)
INSERT INTO branch VALUES (281,'NBgd - og. "Fontana"', 0)
INSERT INTO branch VALUES (282,'NBgd - og. "Milentije Popovi}"', 0)
INSERT INTO branch VALUES (283,'NBgd - og. "4. jul"', 0)
INSERT INTO branch VALUES (284,'NBgd - og. "Be`anija"', 0)
INSERT INTO branch VALUES (285,'NBgd - og. "U`i~ka republika"', 0)
INSERT INTO branch VALUES (286,'NBgd - og. "Bratstvo-jedinstvo"', 0)
INSERT INTO branch VALUES (287,'NBgd - og. "Sava"', 0)
INSERT INTO branch VALUES (288,'NBgd - og. "Kadinja~a"', 0)
INSERT INTO branch VALUES (289,'NBgd - De~je odeljenje', 0)
INSERT INTO branch VALUES (290,'NBgd - og. "Pionir"', 0)
INSERT INTO branch VALUES (310,'Zemu - B. "Sveti Sava"', 0)
INSERT INTO branch VALUES (311,'Zemu - De~je odeljenje', 0)
INSERT INTO branch VALUES (312,'Zemu - og. "Gornji grad"', 0)
INSERT INTO branch VALUES (313,'Zemu - og. "Zemun Polje"', 0)
INSERT INTO branch VALUES (314,'Zemu - og. "Kara|or|ev trg"', 0)
INSERT INTO branch VALUES (315,'Zemu - og. "Novi grad"', 0)
INSERT INTO branch VALUES (316,'Zemu - og. "Batajnica"', 0)
INSERT INTO branch VALUES (317,'Zemu - og. "Dobanovci"', 0)
INSERT INTO branch VALUES (318,'Zemu - og. "Sur~in"', 0)
INSERT INTO branch VALUES (319,'Zemu - og. "Nova Galenika"', 0)
INSERT INTO branch VALUES (330,'Groc - B. "Ilija Gara{anin"', 0)
INSERT INTO branch VALUES (331,'Groc - De~je odeljenje', 0)
INSERT INTO branch VALUES (332,'Groc - og. "Vr~in"', 0)
INSERT INTO branch VALUES (333,'Groc - og. "Kalu|erica"', 0)
INSERT INTO branch VALUES (350,'Sopo - B. "Milovan Vidakovi}"', 0)
INSERT INTO branch VALUES (351,'Sopo - og. "Mali Po`arevac"', 0)
INSERT INTO branch VALUES (352,'Sopo - og. "Ralja"', 0)
INSERT INTO branch VALUES (353,'Sopo - og. "Roga~a"', 0)
INSERT INTO branch VALUES (400,'Pali - B. "Milutin Boji}"', 0)
INSERT INTO branch VALUES (401,'Pali - og. "Had`ipopovac"', 0)
INSERT INTO branch VALUES (402,'Pali - og. "Stara Karaburma"', 0)
INSERT INTO branch VALUES (403,'Pali - og. "Pero ]etkovi}"', 0)
INSERT INTO branch VALUES (404,'Pali - og. "Marijana Gregoran"', 0)
INSERT INTO branch VALUES (405,'Pali - og. "Padinska skela"', 0)
INSERT INTO branch VALUES (406,'Pali - og. "Bor~a"', 0)
INSERT INTO branch VALUES (407,'Pali - og. "Kote`"', 0)
INSERT INTO branch VALUES (408,'Pali - og. "Ov~a"', 0)
INSERT INTO branch VALUES (409,'Pali - og. "Krnja~a"', 0)
INSERT INTO branch VALUES (420,'Laza - B. "Dimitrije Tucovi}"', 0)
INSERT INTO branch VALUES (421,'Laza - B. "Dimitrije Tucovi}", De~je', 0)
INSERT INTO branch VALUES (422,'Laza - og. u Velikim Crljenima', 0)
INSERT INTO branch VALUES (423,'Laza - og. u Rudovcima', 0)
INSERT INTO branch VALUES (424,'Laza - og. u Junkovcu', 0)
INSERT INTO branch VALUES (440,'Obre - B. "Vlada Aksentijevi}"', 0)
INSERT INTO branch VALUES (441,'Obre - og. u JP za informisanje', 0)
INSERT INTO branch VALUES (442,'Obre - og. u Rojkovcu', 0)
INSERT INTO branch VALUES (443,'Obre - og. u Drenu', 0)
INSERT INTO branch VALUES (444,'Obre - og. u Stublinama', 0)
INSERT INTO branch VALUES (445,'Obre - De~je odeljenje', 0)
INSERT INTO branch VALUES (999,'^lan udru`enih biblioteka', 0)
INSERT INTO location VALUES (000,'Mre`a biblioteka')
INSERT INTO location VALUES (001,'Biblioteka grada Beograda, Pult')
INSERT INTO location VALUES (002,'BGB - De~je o. "^ika Jova Zmaj"')
INSERT INTO location VALUES (003,'BGB - De~je o. "Neven"')
INSERT INTO location VALUES (004,'BGB - Ameri~ki kutak')
INSERT INTO location VALUES (100,'Vo`d - B. "Dositej Obradovi}')
INSERT INTO location VALUES (101,'Vo`d - B. "Dositej Obradovi}", De~je')
INSERT INTO location VALUES (102,'Vo`d - og. "Milorad Pani} Surep"')
INSERT INTO location VALUES (103,'Vo`d - og. "Kara|or|e"')
INSERT INTO location VALUES (104,'Vo`d - og. "Milutin Uskokovi}"')
INSERT INTO location VALUES (105,'Vo`d - og. "Stepa Stepanovi}"')
INSERT INTO location VALUES (106,'Vo`d - og. "Filip Vi{nji}"')
INSERT INTO location VALUES (107,'Vo`d - og. "Milan \. Mili}evi}"')
INSERT INTO location VALUES (120,'Vra~ - B. "Petar Ko~i}"')
INSERT INTO location VALUES (121,'Vra~ - B. "Petar Ko~i}", De~je')
INSERT INTO location VALUES (122,'Vra~ - og. "Borislav Peki}"')
INSERT INTO location VALUES (123,'Vra~ - og. "Laza Lazarevi}"')
INSERT INTO location VALUES (124,'Vra~ - og. "Svetozar Markovi}"')
INSERT INTO location VALUES (140,'Zvez - B. "Vuk Karad`i}"')
INSERT INTO location VALUES (141,'Zvez - og. "Radoje Domanovi}"')
INSERT INTO location VALUES (142,'Zvez - og. "Bla`o [}epanovi}"')
INSERT INTO location VALUES (143,'Zvez - og. "Milorad Pani} Surep"')
INSERT INTO location VALUES (144,'Zvez - og. "Dragi{a Vito{evi}"')
INSERT INTO location VALUES (145,'Zvez - og. "Branko Miljkovi}"')
INSERT INTO location VALUES (146,'Zvez - og. "Jefimija"')
INSERT INTO location VALUES (160,'^uka - B. "Laza Kosti}"')
INSERT INTO location VALUES (161,'^uka - og. "Prometej"')
INSERT INTO location VALUES (162,'^uka - og. "Du{ko Radovi}"')
INSERT INTO location VALUES (163,'^uka - og. "Branko ]opi}"')
INSERT INTO location VALUES (164,'^uka - og. "\ura Jak{i}"')
INSERT INTO location VALUES (165,'^uka - og. "Dimitrije Tucovi}"')
INSERT INTO location VALUES (166,'^uka - og. "Cerak"')
INSERT INTO location VALUES (167,'^uka - og. "Ru{anj"')
INSERT INTO location VALUES (168,'^uka - og. "Ostru`nica"')
INSERT INTO location VALUES (180,'Rako - B. "Miodrag Bulatovi}"')
INSERT INTO location VALUES (181,'Rako - og. "Miroslav Anti}"')
INSERT INTO location VALUES (182,'Rako - og. "Du{an Mati}"')
INSERT INTO location VALUES (183,'Rako - og. "Ivo Andri}"')
INSERT INTO location VALUES (184,'Rako - og. "Milo{ Crnjanski"')
INSERT INTO location VALUES (185,'Rako - og. "Isidora Sekuli}"')
INSERT INTO location VALUES (200,'Mlad - B. "Despot Stefan Lazarevi}"')
INSERT INTO location VALUES (201,'Mlad - De~je odeljenje')
INSERT INTO location VALUES (220,'Bara - B. "Jovan Du~i}"')
INSERT INTO location VALUES (221,'Bara - og. "Vrani}"')
INSERT INTO location VALUES (222,'Bara - og. "Banko Radi~evi}", Meljak')
INSERT INTO location VALUES (240,'Savv - B. "Isidora Sekuli}"')
INSERT INTO location VALUES (241,'Savv - De~je odeljenje "Vojislav Ili}"')
INSERT INTO location VALUES (242,'Savv - og. "Jovan Jovanovi} Zmaj"')
INSERT INTO location VALUES (243,'Savv - og. "Veselin Masle{a"')
INSERT INTO location VALUES (244,'Savv - og. "Branko Stankovi}"')
INSERT INTO location VALUES (245,'Savv - og. "Veljko Petrovi}"')
INSERT INTO location VALUES (246,'Savv - punkt BIP')
INSERT INTO location VALUES (260,'Stag - B. "\or|e Jovanovi}"')
INSERT INTO location VALUES (261,'Stag - De~je odeljenje')
INSERT INTO location VALUES (262,'Stag - og. "Jovan Popovi}"')
INSERT INTO location VALUES (263,'Stag - punkt "Energogas"')
INSERT INTO location VALUES (280,'NBgd - B. "Vuk Karad`i}"')
INSERT INTO location VALUES (281,'NBgd - og. "Fontana"')
INSERT INTO location VALUES (282,'NBgd - og. "Milentije Popovi}"')
INSERT INTO location VALUES (283,'NBgd - og. "4. jul"')
INSERT INTO location VALUES (284,'NBgd - og. "Be`anija"')
INSERT INTO location VALUES (285,'NBgd - og. "U`i~ka republika"')
INSERT INTO location VALUES (286,'NBgd - og. "Bratstvo-jedinstvo"')
INSERT INTO location VALUES (287,'NBgd - og. "Sava"')
INSERT INTO location VALUES (288,'NBgd - og. "Kadinja~a"')
INSERT INTO location VALUES (289,'NBgd - De~je odeljenje')
INSERT INTO location VALUES (290,'NBgd - og. "Pionir"')
INSERT INTO location VALUES (310,'Zemu - B. "Sveti Sava"')
INSERT INTO location VALUES (311,'Zemu - De~je odeljenje')
INSERT INTO location VALUES (312,'Zemu - og. "Gornji grad"')
INSERT INTO location VALUES (313,'Zemu - og. "Zemun Polje"')
INSERT INTO location VALUES (314,'Zemu - og. "Kara|or|ev trg"')
INSERT INTO location VALUES (315,'Zemu - og. "Novi grad"')
INSERT INTO location VALUES (316,'Zemu - og. "Batajnica"')
INSERT INTO location VALUES (317,'Zemu - og. "Dobanovci"')
INSERT INTO location VALUES (318,'Zemu - og. "Sur~in"')
INSERT INTO location VALUES (319,'Zemu - og. "Nova Galenika"')
INSERT INTO location VALUES (330,'Groc - B. "Ilija Gara{anin"')
INSERT INTO location VALUES (331,'Groc - De~je odeljenje')
INSERT INTO location VALUES (332,'Groc - og. "Vr~in"')
INSERT INTO location VALUES (333,'Groc - og. "Kalu|erica"')
INSERT INTO location VALUES (350,'Sopo - B. "Milovan Vidakovi}"')
INSERT INTO location VALUES (351,'Sopo - og. "Mali Po`arevac"')
INSERT INTO location VALUES (352,'Sopo - og. "Ralja"')
INSERT INTO location VALUES (353,'Sopo - og. "Roga~a"')
INSERT INTO location VALUES (400,'Pali - B. "Milutin Boji}"')
INSERT INTO location VALUES (401,'Pali - og. "Had`ipopovac"')
INSERT INTO location VALUES (402,'Pali - og. "Stara Karaburma"')
INSERT INTO location VALUES (403,'Pali - og. "Pero ]etkovi}"')
INSERT INTO location VALUES (404,'Pali - og. "Marijana Gregoran"')
INSERT INTO location VALUES (405,'Pali - og. "Padinska skela"')
INSERT INTO location VALUES (406,'Pali - og. "Bor~a"')
INSERT INTO location VALUES (407,'Pali - og. "Kote`"')
INSERT INTO location VALUES (408,'Pali - og. "Ov~a"')
INSERT INTO location VALUES (409,'Pali - og. "Krnja~a"')
INSERT INTO location VALUES (420,'Laza - B. "Dimitrije Tucovi}"')
INSERT INTO location VALUES (421,'Laza - B. "Dimitrije Tucovi}", De~je')
INSERT INTO location VALUES (422,'Laza - og. u Velikim Crljenima')
INSERT INTO location VALUES (423,'Laza - og. u Rudovcima')
INSERT INTO location VALUES (424,'Laza - og. u Junkovcu')
INSERT INTO location VALUES (440,'Obre - B. "Vlada Aksentijevi}"')
INSERT INTO location VALUES (441,'Obre - og. u JP za informisanje')
INSERT INTO location VALUES (442,'Obre - og. u Rojkovcu')
INSERT INTO location VALUES (443,'Obre - og. u Drenu')
INSERT INTO location VALUES (444,'Obre - og. u Stublinama')
INSERT INTO location VALUES (445,'Obre - De~je odeljenje')
INSERT INTO location VALUES (999,'^lan udru`enih biblioteka')
insert into warning_types (id, name, wtext) values (0, 'Opomena', '<war:root xmlns:war="warning"><opomena><zaglavlje><naziv>Biblioteka grada Beograda</naziv><biblioteka>BIBLIOTEKA GRADA BEOGRADA</biblioteka><ogranak>Ogranak </ogranak><sifra>[ifra: 01</sifra><adresa>Knez Mihailova 56</adresa><mesto>11000 Beograd</mesto><bropomenetext/><bropomene/><naslov>OPOMENA</naslov><roktext>rok vra}anja:</roktext></zaglavlje><body><textiznad>Uvidom u na{u evidenciju ustanovili smo da niste u predvi|enom roku vratili pozajmljene knjigu-e:</textiznad><tabelazg><rbr>R.br.</rbr><naslov>Naslov</naslov><autor>Autor</autor><invbroj>Inv.broj</invbroj><signatura>Signatura</signatura><brdana>Br.dana prekora~enja</brdana></tabelazg><textispod>Molimo vas da svoju obavezu isputnite u roku od 3 (tri) dana kako ne bi doslo do primene drugih predvi|enih mera, kao i da prilikom vra}anja knjiga u Biblioiteku grada Beograda, ul. Knez Mihailova 56, izvr{ite obavezu nadoknade tro{kova u iznosu:</textispod><nadoknada1>nadoknada za prekora~enje roka dnevno po svakoj knjizi:</nadoknada1><nadoknada2>nadoknada za tro{kove opomene:</nadoknada2><cena1>3</cena1><cena2>200</cena2><din>din.</din><dodatuma>Ukupno do</dodatuma><napomena>Napomena: Obavezno poneti i ovu opomenu.</napomena></body><podaci><prezime/><ime/><roditelj/><imeroditelja/><adresa/><mesto/><zip/><useridtext>br. ~lanske karte:</useridtext><userid/><docno/><docmesto/><jmbg/></podaci><footer><pojedinacno/><trostrukotext/><biblioteka/><direktor/><ime/></footer></opomena><cirilica>0</cirilica></war:root>')
insert into warning_types (id, name, wtext) values (1, 'Opomena pred utu`enje', '<war:root xmlns:war="warning"><opomena><zaglavlje><naziv>Biblioteka grada Beograda</naziv><biblioteka>BIBLIOTEKA GRADA BEOGRADA</biblioteka><ogranak>Ogranak </ogranak><sifra>[ifra: 01</sifra><adresa>Knez Mihailova 56</adresa><mesto>11000 Beograd</mesto><bropomenetext>Br.opomene:</bropomenetext><bropomene/><naslov>OPOMENA PRED UTU@ENJE</naslov><roktext>rok vra}anja:</roktext></zaglavlje><body><textiznad>Uvidom u na{u evidenciju ustanovili smo da niste u predvi|enom roku vratili pozajmljene knjigu-e:</textiznad><tabelazg><rbr>R.br.</rbr><naslov>Naslov</naslov><autor>Autor</autor><invbroj>Inv.broj</invbroj><signatura>Signatura</signatura><brdana>Br.dana prekora~enja</brdana></tabelazg><textispod>Molimo vas da svoju obavezu isputnite u roku od 3 (tri) dana kako ne bi doslo do primene drugih predvi|enih mera, kao i da prilikom vra}anja knjiga u Biblioiteku grada Beograda, ul. Knez Mihailova 56, izvr{ite obavezu nadoknade tro{kova u iznosu:</textispod><nadoknada1>nadoknada za prekora~enje roka dnevno po svakoj knjizi:</nadoknada1><nadoknada2>nadoknada za tro{kove opomene:</nadoknada2><cena1>3</cena1><cena2>200</cena2><din>din.</din><dodatuma>Ukupno do</dodatuma><napomena/></body><podaci><prezime/><ime/><roditelj>roditelj</roditelj><imeroditelja/><adresa/><mesto/><zip/><useridtext>br. ~lanske karte:</useridtext><userid/><docno>br. li~ne karte: </docno><docmesto>mesto izdavanja:</docmesto><jmbg>JMBG:</jmbg></podaci><footer><pojedinacno>Pojedina~na vrednost knjiga:</pojedinacno><trostrukotext>Trostruka vrednost knjiga:</trostrukotext><biblioteka>Biblioteka grada Beograda</biblioteka><direktor>Direktor</direktor><ime>Jovan Radulovi}</ime></footer></opomena><cirilica>0</cirilica></war:root>')
insert into warning_types (id, name, wtext) values (2, 'Opomena pred utu`enje - tre}a lica', '<war:root xmlns:war="warning"><opomena><zaglavlje><naziv>Biblioteka grada Beograda</naziv><biblioteka>BIBLIOTEKA GRADA BEOGRADA</biblioteka><ogranak>Ogranak </ogranak><sifra>[ifra: 01</sifra><adresa>Knez Mihailova 56</adresa><mesto>11000 Beograd</mesto><bropomenetext>Br.opomene:</bropomenetext><bropomene/><naslov>OPOMENA PRED UTU@ENJE</naslov><roktext>rok vra}anja:</roktext></zaglavlje><body><textiznad>Uvidom u na{u evidenciju ustanovili smo da niste u predvi|enom roku vratili pozajmljene knjigu-e:</textiznad><tabelazg><rbr>R.br.</rbr><naslov>Naslov</naslov><autor>Autor</autor><invbroj>Inv.broj</invbroj><signatura>Signatura</signatura><brdana>Br.dana prekora~enja</brdana></tabelazg><textispod>Molimo vas da svoju obavezu isputnite u roku od 3 (tri) dana kako ne bi doslo do primene drugih predvi|enih mera, kao i da prilikom vra}anja knjiga u Biblioiteku grada Beograda, ul. Knez Mihailova 56, izvr{ite obavezu nadoknade tro{kova u iznosu:</textispod><nadoknada1>nadoknada za prekora~enje roka dnevno po svakoj knjizi:</nadoknada1><nadoknada2>nadoknada za tro{kove opomene:</nadoknada2><cena1>3</cena1><cena2>200</cena2><din>din.</din><dodatuma>Ukupno do</dodatuma><napomena/></body><podaci><prezime/><ime/><roditelj>roditelj</roditelj><imeroditelja/><adresa/><mesto/><zip/><useridtext>br. ~lanske karte:</useridtext><userid/><docno>br. li~ne karte: </docno><docmesto>mesto izdavanja:</docmesto><jmbg>JMBG:</jmbg></podaci><footer><pojedinacno/><trostrukotext>Trostruka vrednost knjiga:</trostrukotext><biblioteka>Biblioteka grada Beograda</biblioteka><direktor>Direktor</direktor><ime>Jovan Radulovi}</ime></footer></opomena><cirilica>0</cirilica></war:root>')
INSERT INTO groups VALUES ('x',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0)
insert into block_reasons (id, name) values (1, 'Istekla ~lanarina')
insert into block_reasons (id, name) values (2, 'Poslata opomena')
insert into block_reasons (id, name) values (3, 'Bibl')
CREATE SEQUENCE LENDIDSEQ START WITH 1 NOCACHE