CREATE TABLE InvCounters (counter_id VARCHAR2(50) NOT NULL, last_value INTEGER NOT NULL, PRIMARY KEY (counter_id))
CREATE TABLE misc_counters (counter_name VARCHAR(30) not null, counter_value INTEGER not null, primary key (counter_name))
INSERT INTO misc_counters (counter_name, counter_value) VALUES ('RN', 0)
CREATE TABLE Delimiters (configID integer NOT NULL, wordDelims VARCHAR(100) UNICODE NOT NULL , sentDelims VARCHAR(20) UNICODE NOT NULL, PRIMARY KEY (configID))
CREATE TABLE Documents ( doc_id integer NOT NULL, document long unicode, PRIMARY KEY (doc_id))
CREATE SEQUENCE DocSeq NOCACHE
CREATE TABLE Doc_shadow ( doc_id integer NOT NULL, PRIMARY KEY (doc_id))
CREATE TABLE Prefixes ( name char(2) NOT NULL, type integer NOT NULL , indextype int NOT NULL, PRIMARY KEY (name))
CREATE TABLE Prefix_contents ( prefID integer NOT NULL, pref_name char(2) NOT NULL , content long unicode, doc_id integer NOT NULL, PRIMARY KEY (prefID), FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE )
CREATE INDEX Pref_cont_1 ON Prefix_contents ( doc_id, pref_name )
CREATE SEQUENCE PrefContSeq NOCACHE
CREATE TABLE Prefix_map ( id integer NOT NULL, pref_name char(2) NOT NULL , subfield_id VARCHAR(8) UNICODE NOT NULL, PRIMARY KEY (id))
CREATE SEQUENCE PrefixMapSeq NOCACHE
CREATE TABLE pref_AB ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_AB_in ON pref_AB (content)
CREATE TABLE pref_AM ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_AM_in ON pref_AM (content)
CREATE TABLE pref_AN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_AN_in ON pref_AN (content)
CREATE TABLE pref_AP ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_AP_in ON pref_AP (content)
CREATE TABLE pref_AT ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_AT_in ON pref_AT (content)
CREATE TABLE pref_AU ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_AU_in ON pref_AU (content)
CREATE TABLE pref_BI ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_BI_in ON pref_BI (content)
CREATE TABLE pref_BN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_BN_in ON pref_BN (content)
CREATE TABLE pref_CB ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CB_in ON pref_CB (content)
CREATE TABLE pref_CC ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CC_in ON pref_CC (content)
CREATE TABLE pref_CD ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CD_in ON pref_CD (content)
CREATE TABLE pref_CH ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CH_in ON pref_CH (content)
CREATE TABLE pref_CL ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CL_in ON pref_CL (content)
CREATE TABLE pref_CN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CN_in ON pref_CN (content)
CREATE TABLE pref_CO ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CO_in ON pref_CO (content)
CREATE TABLE pref_CP ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CP_in ON pref_CP (content)
CREATE TABLE pref_CR ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CR_in ON pref_CR (content)
CREATE TABLE pref_CS ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_CS_in ON pref_CS (content)
CREATE TABLE pref_DA ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_DA_in ON pref_DA (content)
CREATE TABLE pref_DC ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_DC_in ON pref_DC (content)
CREATE TABLE pref_DE ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_DE_in ON pref_DE (content)
CREATE TABLE pref_DR ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_DR_in ON pref_DR (content)
CREATE TABLE pref_DS ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_DS_in ON pref_DS (content)
CREATE TABLE pref_DT ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_DT_in ON pref_DT (content)
CREATE TABLE pref_ES ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_ES_in ON pref_ES (content)
CREATE TABLE pref_FC ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_FC_in ON pref_FC (content)
CREATE TABLE pref_FD ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_FD_in ON pref_FD (content)
CREATE TABLE pref_FI ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_FI_in ON pref_FI (content)
CREATE TABLE pref_FN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_FN_in ON pref_FN (content)
CREATE TABLE pref_FQ ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_FQ_in ON pref_FQ (content)
CREATE TABLE pref_FS ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_FS_in ON pref_FS (content)
CREATE TABLE pref_GE ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_GE_in ON pref_GE (content)
CREATE TABLE pref_GM ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_GM_in ON pref_GM (content)
CREATE TABLE pref_GN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_GN_in ON pref_GN (content)
CREATE TABLE pref_GS ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_GS_in ON pref_GS (content)
CREATE TABLE pref_IC ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_IC_in ON pref_IC (content)
CREATE TABLE pref_II ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_II_in ON pref_II (content)
CREATE TABLE pref_IN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_IN_in ON pref_IN (content)
CREATE TABLE pref_IR ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_IR_in ON pref_IR (content)
CREATE TABLE pref_KT ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_KT_in ON pref_KT (content)
CREATE TABLE pref_KW ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_KW_in ON pref_KW (content)
CREATE TABLE pref_LA ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_LA_in ON pref_LA (content)
CREATE TABLE pref_LC ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_LC_in ON pref_LC (content)
CREATE TABLE pref_LI ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_LI_in ON pref_LI (content)
CREATE TABLE pref_LO ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_LO_in ON pref_LO (content)
CREATE TABLE pref_MR ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_MR_in ON pref_MR (content)
CREATE TABLE pref_ND ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_ND_in ON pref_ND (content)
CREATE TABLE pref_NM ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_NM_in ON pref_NM (content)
CREATE TABLE pref_NT ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_NT_in ON pref_NT (content)
CREATE TABLE pref_P2 ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_P2_in ON pref_P2 (content)
CREATE TABLE pref_PA ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_PA_in ON pref_PA (content)
CREATE TABLE pref_PM ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_PM_in ON pref_PM (content)
CREATE TABLE pref_PN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_PN_in ON pref_PN (content)
CREATE TABLE pref_PP ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_PP_in ON pref_PP (content)
CREATE TABLE pref_PR ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_PR_in ON pref_PR (content)
CREATE TABLE pref_PU ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_PU_in ON pref_PU (content)
CREATE TABLE pref_PY ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_PY_in ON pref_PY (content)
CREATE TABLE pref_RE ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_RE_in ON pref_RE (content)
CREATE TABLE pref_RJ ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_RJ_in ON pref_RJ (content)
CREATE TABLE pref_RN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_RN_in ON pref_RN (content)
CREATE TABLE pref_RS ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_RS_in ON pref_RS (content)
CREATE TABLE pref_RT ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_RT_in ON pref_RT (content)
CREATE TABLE pref_SC ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_SC_in ON pref_SC (content)
CREATE TABLE pref_SG ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_SG_in ON pref_SG (content)
CREATE TABLE pref_SI ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_SI_in ON pref_SI (content)
CREATE TABLE pref_SK ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_SK_in ON pref_SK (content)
CREATE TABLE pref_SN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_SN_in ON pref_SN (content)
CREATE TABLE pref_SP ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_SP_in ON pref_SP (content)
CREATE TABLE pref_SR ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_SR_in ON pref_SR (content)
CREATE TABLE pref_SS ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_SS_in ON pref_SS (content)
CREATE TABLE pref_ST ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_ST_in ON pref_ST (content)
CREATE TABLE pref_SU ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_SU_in ON pref_SU (content)
CREATE TABLE pref_TA ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_TA_in ON pref_TA (content)
CREATE TABLE pref_TI ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_TI_in ON pref_TI (content)
CREATE TABLE pref_TN ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_TN_in ON pref_TN (content)
CREATE TABLE pref_TP ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_TP_in ON pref_TP (content)
CREATE TABLE pref_TS ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_TS_in ON pref_TS (content)
CREATE TABLE pref_TY ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_TY_in ON pref_TY (content)
CREATE TABLE pref_UG ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_UG_in ON pref_UG (content)
CREATE TABLE pref_US ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_US_in ON pref_US (content)
CREATE TABLE pref_UT ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_UT_in ON pref_UT (content)
CREATE TABLE pref_Y1 ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_Y1_in ON pref_Y1 (content)
CREATE TABLE pref_Y2 ( doc_id integer NOT NULL , content VARCHAR(255) UNICODE NOT NULL , pref_id integer NOT NULL , word_pos integer NOT NULL , sent_pos integer NOT NULL, FOREIGN KEY (doc_id) REFERENCES doc_shadow (doc_id) ON DELETE CASCADE)
CREATE INDEX pref_Y2_in ON pref_Y2 (content)
INSERT INTO Prefixes (name, type, indextype) VALUES ('AN', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('AT', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CD', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CO', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('DR', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('FQ', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('KW', 2, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('P2', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('RJ', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('RS', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('RT', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('SC', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('SS', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('TY', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('US', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('Y1', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('Y2', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('DE', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('FI', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('LI', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('ND', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('SR', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('IR', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('ES', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('GS', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('II', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('NM', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('NT', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('PA', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('PM', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('PR', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CB', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('FN', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('PN', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('TS', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('TI', 3, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('AU', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('BN', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('SN', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('SP', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('PY', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('LA', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('PU', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('PP', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('LO', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('DT', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CC', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('IC', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CS', 2, 1)
INSERT INTO Prefixes (name, type, indextype) VALUES ('LC', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('GM', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('SU', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CP', 2, 1)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CR', 2, 1)
INSERT INTO Prefixes (name, type, indextype) VALUES ('DC', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('UG', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('SG', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('SI', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('IN', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('DS', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('ST', 2, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('AM', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('AP', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CL', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('BI', 2, 1)
INSERT INTO Prefixes (name, type, indextype) VALUES ('SK', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('TP', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('RE', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('FD', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('FC', 2, 2)
INSERT INTO Prefixes (name, type, indextype) VALUES ('KT', 1, 1)
INSERT INTO Prefixes (name, type, indextype) VALUES ('AB', 1, 1)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CN', 1, 1)
INSERT INTO Prefixes (name, type, indextype) VALUES ('UT', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('TN', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('GN', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('CH', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('FS', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('GE', 1, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('DA', 2, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('ID', 2, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('RN', 2, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('MR', 2, 3)
INSERT INTO Prefixes (name, type, indextype) VALUES ('TA', 2, 2)
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AT', '531a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AT', '531b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '700a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '700b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '701a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '701b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '702a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '702b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '900a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '900b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '901a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '901b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '902a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AU', '902b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'BI', '992b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'BN', '010a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'BN', '010z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CC', '105b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CD', '040a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CL', '225a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CL', '225e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CL', '225i')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CL', '225h')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CO', '102a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CP', '710e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CP', '711e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CP', '712e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CP', '910e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CP', '911e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CP', '912e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CR', '000c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '503a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '503b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '710a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '710b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '711a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '711b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '712a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '712b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '910a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '910b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '911a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '911b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '912a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CS', '912b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'DC', '675a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'DC', '675u')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'DR', '328f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'DT', '001c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FC', '7008')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FC', '7018')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FC', '7028')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FD', '7009')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FD', '7019')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FD', '7029')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FD', '9009')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FD', '9019')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FD', '9029')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FQ', '110b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'GM', '200b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'IC', '105a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '200a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '200c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '200d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '200i')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '327a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '330a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '500a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '501a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '510a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '511a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '512a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '513a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '514a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '515a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '516a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '517a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '530a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '531a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '532a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '540a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '6006')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '600a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '600b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '600c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '600d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '600f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '600w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '600x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '600y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '600z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '6016')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601g')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601h')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '601z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '6026')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '602a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '602f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '602w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '602x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '602y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '602z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '6056')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605h')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605i')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605k')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605l')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605m')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605n')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605q')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '605z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '6062')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '6066')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '606a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '606w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '606x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '606y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '606z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '6076')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '607a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '607w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '607x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '607y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '607z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '6086')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '608a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '608w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '608x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '608y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '608z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '6096')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '609a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '609w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '609x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '609y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '609z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '610a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '610b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '610z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KW', '627a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'LA', '101a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'LC', '105f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'LO', '101c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PP', '210a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PU', '210c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PU', '992r')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PY', '100c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'P2', '100d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'RE', '102b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'RJ', '391a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'RS', '001a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'RT', '001b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SC', '011y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SK', '992a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SN', '011a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SN', '011z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SP', '011e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SP', '011c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SS', '100b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SU', '200e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SU', '512e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TA', '7004')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TA', '7014')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TA', '7024')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TA', '9004')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TA', '9014')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TA', '9024')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '200a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '200c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '200d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '200i')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '500a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '501a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '510a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '511a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '512a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '513a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '514a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '515a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '516a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '517a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '530a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '531a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '532a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TI', '540a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TP', '105i')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TY', '110a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'UG', '675b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'US', '675s')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'Y1', '328d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'Y2', '328e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AM', '996v')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AM', '997v')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AP', '996w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AP', '997w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'DA', '996o')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'DA', '997o')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'DE', '9968')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FI', '9964')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FI', '9974')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'IN', '996f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'IN', '997f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'LI', '996p')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'LI', '997p')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '996x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '996y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '996z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '9961')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '9967')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '997x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '997y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '997z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '9971')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ND', '9977')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SG', '996d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SG', '996e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SG', '997d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SG', '997e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SI', '998b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SR', '9962')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'SR', '9972')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'IR', '996r')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'IR', '997r')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ST', '996q')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ST', '997q')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ES', '205a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ES', '205d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ES', '205f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ES', '205g')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'ES', '205b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'GS', '300a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'II', '320a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'NM', '210g')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'NT', '200h')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'NT', '200v')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PA', '210b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PM', '210e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PR', '9963')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PR', '9973')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'AB', '330a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CB', '601a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CB', '601b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CB', '601c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CB', '601d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CB', '601e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CB', '601f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CB', '601g')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CB', '601h')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CB', '601w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CH', '608a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CH', '608w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CH', '608x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CH', '608y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CH', '608z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'CN', '327a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FN', '602a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FN', '602f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FN', '602w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FN', '602x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FN', '602y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FN', '602z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FS', '609a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FS', '609w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FS', '609x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FS', '609y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'FS', '609z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'GE', '627a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'GN', '607a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'GN', '607w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'GN', '607x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'GN', '607y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'GN', '607z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'KT', '530a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PN', '600a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PN', '600b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PN', '600c')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PN', '600d')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PN', '600e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PN', '600f')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PN', '600w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PN', '600x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'PN', '600y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TN', '606a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TN', '606w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TN', '606x')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TN', '606y')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TN', '606z')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TS', '605a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TS', '605h')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TS', '605i')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TS', '605k')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TS', '605l')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TS', '605m')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TS', '605n')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TS', '605q')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'TS', '605w')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'UT', '610a')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'UT', '610b')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'RN', '001e')
INSERT INTO Prefix_map (id, pref_name, subfield_id) VALUES (PrefixMapSeq.NEXTVAL, 'MR', '4741')
insert into Delimiters (configID, wordDelims, sentDelims) values (1, ', ;:"()[]{}-+/', '.?!')
CREATE TABLE registar_autori (autor VARCHAR(255) UNICODE, original VARCHAR(255) UNICODE)
CREATE INDEX registar_autori_1 ON registar_autori (autor)
CREATE INDEX registar_autori_2 ON registar_autori (original)
CREATE TABLE registar_kolektivni (kolektivac VARCHAR(255) UNICODE)
CREATE INDEX registar_kolektivni_1 ON registar_kolektivni (kolektivac)
CREATE TABLE registar_odr (pojam VARCHAR(255) UNICODE)
CREATE INDEX registar_odr_1 ON registar_odr (pojam)
CREATE TABLE registar_pododr (pojam VARCHAR(255) UNICODE)
CREATE INDEX registar_pododr_1 ON registar_pododr (pojam)
CREATE TABLE registar_zbirke (naziv VARCHAR(255) UNICODE)
CREATE INDEX registar_zbirke_1 ON registar_zbirke (naziv)
CREATE TABLE registar_udk (grupa VARCHAR(255) UNICODE, opis VARCHAR(255) UNICODE)
CREATE INDEX registar_udk_1 ON registar_udk (grupa)
CREATE INDEX registar_udk_2 ON registar_udk (opis)
CREATE INDEX pref_AB_id ON pref_AB (doc_id)
CREATE INDEX pref_AM_id ON pref_AM (doc_id)
CREATE INDEX pref_AN_id ON pref_AN (doc_id)
CREATE INDEX pref_AP_id ON pref_AP (doc_id)
CREATE INDEX pref_AT_id ON pref_AT (doc_id)
CREATE INDEX pref_AU_id ON pref_AU (doc_id)
CREATE INDEX pref_BI_id ON pref_BI (doc_id)
CREATE INDEX pref_BN_id ON pref_BN (doc_id)
CREATE INDEX pref_CB_id ON pref_CB (doc_id)
CREATE INDEX pref_CC_id ON pref_CC (doc_id)
CREATE INDEX pref_CD_id ON pref_CD (doc_id)
CREATE INDEX pref_CH_id ON pref_CH (doc_id)
CREATE INDEX pref_CL_id ON pref_CL (doc_id)
CREATE INDEX pref_CN_id ON pref_CN (doc_id)
CREATE INDEX pref_CO_id ON pref_CO (doc_id)
CREATE INDEX pref_CP_id ON pref_CP (doc_id)
CREATE INDEX pref_CR_id ON pref_CR (doc_id)
CREATE INDEX pref_CS_id ON pref_CS (doc_id)
CREATE INDEX pref_DA_id ON pref_DA (doc_id)
CREATE INDEX pref_DC_id ON pref_DC (doc_id)
CREATE INDEX pref_DE_id ON pref_DE (doc_id)
CREATE INDEX pref_DR_id ON pref_DR (doc_id)
CREATE INDEX pref_DS_id ON pref_DS (doc_id)
CREATE INDEX pref_DT_id ON pref_DT (doc_id)
CREATE INDEX pref_ES_id ON pref_ES (doc_id)
CREATE INDEX pref_FC_id ON pref_FC (doc_id)
CREATE INDEX pref_FD_id ON pref_FD (doc_id)
CREATE INDEX pref_FI_id ON pref_FI (doc_id)
CREATE INDEX pref_FN_id ON pref_FN (doc_id)
CREATE INDEX pref_FQ_id ON pref_FQ (doc_id)
CREATE INDEX pref_FS_id ON pref_FS (doc_id)
CREATE INDEX pref_GE_id ON pref_GE (doc_id)
CREATE INDEX pref_GM_id ON pref_GM (doc_id)
CREATE INDEX pref_GN_id ON pref_GN (doc_id)
CREATE INDEX pref_GS_id ON pref_GS (doc_id)
CREATE INDEX pref_IC_id ON pref_IC (doc_id)
CREATE INDEX pref_II_id ON pref_II (doc_id)
CREATE INDEX pref_IN_id ON pref_IN (doc_id)
CREATE INDEX pref_IR_id ON pref_IR (doc_id)
CREATE INDEX pref_KT_id ON pref_KT (doc_id)
CREATE INDEX pref_KW_id ON pref_KW (doc_id)
CREATE INDEX pref_LA_id ON pref_LA (doc_id)
CREATE INDEX pref_LC_id ON pref_LC (doc_id)
CREATE INDEX pref_LI_id ON pref_LI (doc_id)
CREATE INDEX pref_LO_id ON pref_LO (doc_id)
CREATE INDEX pref_MR_id ON pref_MR (doc_id)
CREATE INDEX pref_ND_id ON pref_ND (doc_id)
CREATE INDEX pref_NM_id ON pref_NM (doc_id)
CREATE INDEX pref_NT_id ON pref_NT (doc_id)
CREATE INDEX pref_P2_id ON pref_P2 (doc_id)
CREATE INDEX pref_PA_id ON pref_PA (doc_id)
CREATE INDEX pref_PM_id ON pref_PM (doc_id)
CREATE INDEX pref_PN_id ON pref_PN (doc_id)
CREATE INDEX pref_PP_id ON pref_PP (doc_id)
CREATE INDEX pref_PR_id ON pref_PR (doc_id)
CREATE INDEX pref_PU_id ON pref_PU (doc_id)
CREATE INDEX pref_PY_id ON pref_PY (doc_id)
CREATE INDEX pref_RE_id ON pref_RE (doc_id)
CREATE INDEX pref_RJ_id ON pref_RJ (doc_id)
CREATE INDEX pref_RN_id ON pref_RN (doc_id)
CREATE INDEX pref_RS_id ON pref_RS (doc_id)
CREATE INDEX pref_RT_id ON pref_RT (doc_id)
CREATE INDEX pref_SC_id ON pref_SC (doc_id)
CREATE INDEX pref_SG_id ON pref_SG (doc_id)
CREATE INDEX pref_SI_id ON pref_SI (doc_id)
CREATE INDEX pref_SK_id ON pref_SK (doc_id)
CREATE INDEX pref_SN_id ON pref_SN (doc_id)
CREATE INDEX pref_SP_id ON pref_SP (doc_id)
CREATE INDEX pref_SR_id ON pref_SR (doc_id)
CREATE INDEX pref_SS_id ON pref_SS (doc_id)
CREATE INDEX pref_ST_id ON pref_ST (doc_id)
CREATE INDEX pref_SU_id ON pref_SU (doc_id)
CREATE INDEX pref_TI_id ON pref_TI (doc_id)
CREATE INDEX pref_TN_id ON pref_TN (doc_id)
CREATE INDEX pref_TP_id ON pref_TP (doc_id)
CREATE INDEX pref_TS_id ON pref_TS (doc_id)
CREATE INDEX pref_TY_id ON pref_TY (doc_id)
CREATE INDEX pref_UG_id ON pref_UG (doc_id)
CREATE INDEX pref_US_id ON pref_US (doc_id)
CREATE INDEX pref_UT_id ON pref_UT (doc_id)
CREATE INDEX pref_Y1_id ON pref_Y1 (doc_id)
CREATE INDEX pref_Y2_id ON pref_Y2 (doc_id)
