package com.gint.app.bisis.editor.recordstats.zr;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRXmlDataSource;

import com.gint.app.bisis.editor.Environment;
import com.gint.app.bisis.editor.recordstats.RecordReport;
import com.gint.app.bisis4.common.records.Record;
import com.gint.app.bisis4.common.records.RecordFactory;
import com.gint.app.bisis4.common.records.RecordID;
import com.gint.util.xml.XMLUtils;

public class StanjeFondaPoJezicima extends RecordReport {
  public void execute() {
    try {
      Connection conn = Environment.getConnection();
      Statement stmt = conn.createStatement();
      ResultSet rset = stmt.executeQuery("SELECT count(*) FROM documents");
      rset.next();
      totalRecords = rset.getInt(1);
      rset.close();
      stmt.close();
//      totalRecords = 129487;
      if (rp.isCancelled())
        return;
      rp.setMaximum(totalRecords);
      rp.setValue(0);
      int count = 0;
      stmt = conn.createStatement();
      rset = stmt.executeQuery("SELECT doc_id, document FROM documents");
      while (rset.next()) {
        String rezance = rset.getString(2);
        if (rezance == null)
          continue;
        Record rec = RecordFactory.fromUNIMARC(rezance);
        if (rec == null)
          continue;
        rec.setRecordID(new RecordID(0, rset.getInt(1)));
        if (rp.isCancelled()) {
          rset.close();
          stmt.close();
          return;
        }
        rp.setValue(++count);
        handleRecord(rec);
      }
      rset.close();
      stmt.close();
      
//    //java.io.RandomAccessFile in = new java.io.RandomAccessFile("D:/BISIS/vojvodina/Zrenjanin/BISIS-2005-09-09/records-2005-09-09-11-55.dat", "r");
//    java.io.RandomAccessFile in = new java.io.RandomAccessFile("/home/branko/BISIS_backup/BISIS-2005-12-01/records-2005-12-01-01-49.dat", "r");
//    String line = "";
//    while ((line = in.readLine()) != null) {
//      line = line.trim();
//      rp.setValue(++count);
//      if (line.equals(""))
//        continue;
//      Record rec = RecordFactory.fromUNIMARC(line);
//      rec.setRecordID(new RecordID(0, count));
//      handleRecord(rec);
//    }
//    in.close();
    
      List branchList = new ArrayList();
      branchList.addAll(items.values());
      Collections.sort(branchList);
      
      StringBuffer buff = new StringBuffer();
      buff.append("<report>");
      Iterator it = branchList.iterator();
      while (it.hasNext())
        buff.append(it.next().toString());
      
      buff.append("</report>\n");

      if (params == null)
        params = new HashMap();
      params.put("today", sdf.format(new Date()));

      JRXmlDataSource dataSource = new JRXmlDataSource(
          XMLUtils.getDocumentFromString(buff.toString()), "/report/item");

      JasperPrint jp = JasperFillManager.fillReport(
          StanjeFondaPoUDK.class.getResource(
            "/com/gint/app/bisis/editor/recordstats/zr/StanjeFondaPoJezicima.jasper")
          .openStream(), params, dataSource);
      
      rp.setReport(jp);
      rp.setProblems(problems.toString());
      rp.setFinished(true);
    } catch (Exception ex) {
      ex.printStackTrace();
    }
  }
  
  public void handleRecord(Record rec) {
    String code = rec.getSubfieldContent("101a");
    if (code == null) {
      problems.append("Nedostaje 101a (jezik) u zapisu: " + rec.getRecordID().getLocalRecordID() + "\n");
      return;
    }
    List primerci = rec.getFields("996"); 
    Item item = getItem(code);
    item.count += primerci.size();
  }
  
  public class Item implements Comparable {
    public String code;
    public int count;
    
    public int compareTo(Object o) {
      Item i = (Item)o;
      return code.compareTo(i.code);
    }
    
    public String toString() {
      StringBuffer buff = new StringBuffer();
      buff.append("  <item>\n    <code>");
      buff.append(code);
      buff.append("</code>\n    <text>");
      buff.append(getLang(code));
      buff.append("</text>\n    <count>");
      buff.append(count);
      buff.append("</count>\n  </item>\n");
      return buff.toString();
    }
  }
  
  public Item getItem(String code) {
    Item item = (Item)items.get(code);
    if (item == null) {
      item = new Item();
      item.code = code;
      item.count = 0;
      items.put(code, item);
    }
    return item;
  }
  
  public String getLang(String code) {
    String lang = (String)languages.get(code);
    if (lang == null)
      return " ";
    return lang;
  }
  
  int totalRecords = 0;
  SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
  HashMap items = new HashMap();
  
  static HashMap languages = new HashMap();
  static {
    languages.put("aar","Afar");
    languages.put("abk","Abhaski");
    languages.put("ace","Akineze");
    languages.put("ach","A\u010doli");
    languages.put("ada","Adangme");
    languages.put("ady","Adyghe");
    languages.put("afa","Afroazijski (ostali)");
    languages.put("afh","Afrihili");
    languages.put("afr","Afrikaans");
    languages.put("ajm","Aljamia");
    languages.put("aka","Akan");
    languages.put("akk","Akadski");
    languages.put("alb","Albanski");
    languages.put("ale","Aleutski");
    languages.put("alg","Algonkinski jezici");
    languages.put("amh","Amharski");
    languages.put("ang","Anglosaksonski (450-1100)");
    languages.put("apa","Apa\u0161ki");
    languages.put("ara","Arapski");
    languages.put("arc","Aramejski");
    languages.put("arg","Aragonski");
    languages.put("arm","Jermenski");
    languages.put("arn","Araukanski");
    languages.put("arp","Arapaho");
    languages.put("art","ve\u0161ta\u010dki (drugi)");
    languages.put("arw","Aravak");
    languages.put("asm","Asamski");
    languages.put("ast","Asturian; Bable");
    languages.put("ath","Athapaskanski jezici");
    languages.put("aus","australijski jezici");
    languages.put("ava","Avarski");
    languages.put("ave","Avesti\u010dki");
    languages.put("awa","Avadhi");
    languages.put("aym","Ajmara");
    languages.put("aze","Azerbejd\u017eanski");
    languages.put("bad","Banda");
    languages.put("bai","Bamileke languages");
    languages.put("bak","Ba\u0161kirski");
    languages.put("bal","Balu\u010di");
    languages.put("bam","Bambara");
    languages.put("ban","Bali");
    languages.put("baq","Baskijski");
    languages.put("bas","Basa");
    languages.put("bat","Balti\u010dki (ostali)");
    languages.put("bej","Bed\u017ea");
    languages.put("bel","Beloruski");
    languages.put("bem","Bemba");
    languages.put("ben","Bengalski");
    languages.put("ber","Berberski jezici");
    languages.put("bho","Bhod\u017epuri");
    languages.put("bih","Bihari");
    languages.put("bik","Bikol");
    languages.put("bin","Bini");
    languages.put("bis","Bislama");
    languages.put("bla","Siksika / Blackfoot");
    languages.put("bnt","Bantu (ostali)");
    languages.put("bos","Bosanski (Bo\u0161nja\u010dki)");
    languages.put("bra","Brad\u017e");
    languages.put("bre","Bretonski");
    languages.put("btk","Batak (Indonezija)");
    languages.put("bua","Buriat");
    languages.put("bug","Bugi");
    languages.put("bul","Bugarski");
    languages.put("bur","Burmanski");
    languages.put("byn","Blin / Bilin");
    languages.put("cad","Kado");
    languages.put("cai","Centralnoameri\u010dki indijanski (ostali)");
    languages.put("cam","Kmerski");
    languages.put("car","Karipski");
    languages.put("cat","Katalanski");
    languages.put("cau","Kavkaski (ostali)");
    languages.put("ceb","Kebuanski");
    languages.put("cha","Chamorro");
    languages.put("chb","\u017cib\u010da");
    languages.put("che","\u017ce\u010denski");
    languages.put("chg","\u017cagatai");
    languages.put("chi","Kineski");
    languages.put("chk","Chuukese");
    languages.put("chm","Mari");
    languages.put("chn","\u017cinuk \u017eargon");
    languages.put("cho","Chocktaw");
    languages.put("chp","Chipewyan");
    languages.put("chr","\u017ceroki");
    languages.put("chu","Crkvenoslovenski");
    languages.put("chv","\u017cuva\u0161ki");
    languages.put("chy","\u017cejenski");
    languages.put("cmc","Chamic languages");
    languages.put("cop","Koptski");
    languages.put("cor","Cornish");
    languages.put("cos","Korzikanski");
    languages.put("cpe","Kreolski i pidgin, na osnovi engleskog (ostali)");
    languages.put("cpf","Kreolski i pidgin, na osnovi francuskog (ostali)");
    languages.put("cpp","Kreolski i pidgin, na osnovi portugalskog (ostali)");
    languages.put("cre","Kri");
    languages.put("crh","Krimski tatarski / krimski turski");
    languages.put("crp","Kreolski i pidgin (ostali)");
    languages.put("csb","Kashubian");
    languages.put("cus","Ku\u0161itski (ostali)");
    languages.put("cze","\u017ce\u0161ki");
    languages.put("dak","Dakota");
    languages.put("dan","Danski");
    languages.put("del","Delaware");
    languages.put("den","Slave (Athapascan)");
    languages.put("dgr","Dogrib");
    languages.put("din","Dinka");
    languages.put("div","Divehi");
    languages.put("doi","Dogri");
    languages.put("dra","Dravidski (ostali)");
    languages.put("dsb","Donji Lužičko-srpski (Lower Sorbian)");
    languages.put("dua","Duala");
    languages.put("dum","Srednjoholandski (1050-1350)");
    languages.put("dut","Holandski, Flamanski");
    languages.put("dyu","Dyula");
    languages.put("dzo","Dzongkha");
    languages.put("efi","Efik");
    languages.put("egy","Egipatski (stari)");
    languages.put("eka","Ekajuk");
    languages.put("elx","Elamitski");
    languages.put("eng","Engleski");
    languages.put("enm","Srednjoengleski (1100-1500)");
    languages.put("epo","Esperanto");
    languages.put("esk","Eskimski");
    languages.put("est","Estonski");
    languages.put("eth","Etiopski");
    languages.put("ewe","Ewe");
    languages.put("ewo","Ewondo");
    languages.put("fan","Fang");
    languages.put("far","Faroese");
    languages.put("fat","Fanti");
    languages.put("fij","Fijian");
    languages.put("fil","Filipinski");
    languages.put("fin","Finski");
    languages.put("fiu","Ugrofinski (ostali)");
    languages.put("fon","Fon");
    languages.put("fre","Francuski");
    languages.put("frm","Srednjofrancuski (1400-1600)");
    languages.put("fro","Starofrancuski (842-1400)");
    languages.put("fry","Frizijski");
    languages.put("ful","Fulah");
    languages.put("fur","Friulian");
    languages.put("gaa","Ga");
    languages.put("gal","Galla");
    languages.put("gay","Gayo");
    languages.put("gba","Gbaya");
    languages.put("gem","Germanski (ostali)");
    languages.put("geo","Gruzijski");
    languages.put("ger","Nema\u010dki");
    languages.put("gez","Geez");
    languages.put("gil","Gilbertese");
    languages.put("gla","Gelik / \u0160kotski gelik");
    languages.put("gle","Irski");
    languages.put("glg","Gallegan");
    languages.put("glv","Manx");
    languages.put("gmh","Srednjovisokonema\u010dki (1050-1500)");
    languages.put("goh","Starovisokonema\u010dki (750-1050)");
    languages.put("gon","Gondski");
    languages.put("gor","Gorontalo");
    languages.put("got","Gotski");
    languages.put("grb","Grebo");
    languages.put("grc","Starogr\u010dki (-1453)");
    languages.put("gre","Gr\u010dki (1453-)");
    languages.put("gua","Guarani");
    languages.put("guj","Gud\u017earati");
    languages.put("gwi","Gwich'in");
    languages.put("hai","Haida");
    languages.put("hat","Haitian / Haitian Creole");
    languages.put("hau","Hausa");
    languages.put("haw","Havajski");
    languages.put("heb","Hebrejski");
    languages.put("her","Herero");
    languages.put("hil","Hiligaynon");
    languages.put("him","Hima\u010dali");
    languages.put("hin","Hindi");
    languages.put("hit","Hittite");
    languages.put("hmn","Hmong");
    languages.put("hmo","Hiri motu");
    languages.put("hrv","Hrvatski");
    languages.put("hsb","Gornji Lu\u017ei\u010dko-srpski (Upper Sorbian)");
    languages.put("hun","Ma\u0111arski");
    languages.put("hup","Hupa");
    languages.put("iba","Iban");
    languages.put("ibo","Igbo");
    languages.put("ice","Islandski");
    languages.put("ido","Ido");
    languages.put("iii","Sichuan Yi");
    languages.put("ijo","Ijo");
    languages.put("iku","Inuktitut");
    languages.put("ile","Interlingue");
    languages.put("ilo","Iloko");
    languages.put("ina","Interlingua (International Auxiliary Language Association)");
    languages.put("inc","Indijski (ostali)");
    languages.put("ind","Indonezijski");
    languages.put("ine","Indoevropski (ostali)");
    languages.put("inh","Ingush");
    languages.put("ipk","Inupiak");
    languages.put("ira","Iranski (ostali)");
    languages.put("iro","Irokeski jezici");
    languages.put("ita","Italijanski");
    languages.put("jav","Javanski");
    languages.put("jbo","Lojban");
    languages.put("jpn","Japanski");
    languages.put("jpr","Judeo-Persian");
    languages.put("jrb","Judeo-Arabic");
    languages.put("kaa","Kara-Kalpak");
    languages.put("kab","Kabilski");
    languages.put("kac","Kachin");
    languages.put("kal","Kalaallisut / Greenlandic");
    languages.put("kam","Kamba");
    languages.put("kan","Kannada");
    languages.put("kar","Karen");
    languages.put("kas","Ka\u0161mirski");
    languages.put("kau","Kanuri");
    languages.put("kaw","Kavi");
    languages.put("kaz","Kazahski");
    languages.put("kbd","Kabardian");
    languages.put("kha","Khasi");
    languages.put("khi","Khoisan (other)");
    languages.put("khm","Kmerski");
    languages.put("kho","Khotanese");
    languages.put("kik","Kikuyu");
    languages.put("kin","Kinyarwanda");
    languages.put("kir","Kirgiski");
    languages.put("kmb","Kimbundu");
    languages.put("kok","Konkani");
    languages.put("kom","Komi");
    languages.put("kon","Kongo");
    languages.put("kor","Korejski");
    languages.put("kos","Kosraean");
    languages.put("kpe","Kpelle");
    languages.put("krc","Karachay-Balkar");
    languages.put("kro","Kru");
    languages.put("kru","Kurukh");
    languages.put("kua","Kuanyama / Kwanyama");
    languages.put("kur","Kurdski");
    languages.put("kus","Kusai");
    languages.put("kut","Kutenai");
    languages.put("lad","Ladino");
    languages.put("lah","Lahnda");
    languages.put("lam","Lamba");
    languages.put("lan","Langdok (posle 1500)");
    languages.put("lao","Lao");
    languages.put("lap","Laponski");
    languages.put("lat","Latinski");
    languages.put("lav","Letonski");
    languages.put("lez","Lezghian");
    languages.put("lim","Limburgan / Limburgish");
    languages.put("lin","Lingala");
    languages.put("lit","Litvanski");
    languages.put("lol","Mongo");
    languages.put("loz","Lozi");
    languages.put("ltz","Luxembur\u0161ki");
    languages.put("lua","Luba-Lulua");
    languages.put("lub","Luba-Katanga");
    languages.put("lug","Ganda");
    languages.put("lui","Luiseno");
    languages.put("lun","Lunda");
    languages.put("luo","Luo (Kenija i Tanzanija)");
    languages.put("lus","Lushai");
    languages.put("mac","Makedonski");
    languages.put("mad","Madurski");
    languages.put("mag","Magahi");
    languages.put("mah","Mar\u0161alski");
    languages.put("mai","Maithili");
    languages.put("mak","Makasar");
    languages.put("mal","Malajalamski");
    languages.put("man","Mandingo");
    languages.put("mao","Maorski");
    languages.put("map","Austronezijski (ostali)");
    languages.put("mar","Marathi");
    languages.put("mas","Masai");
    languages.put("max","Manski");
    languages.put("may","Malajski");
    languages.put("mdf","Moksha");
    languages.put("mdr","Mandar");
    languages.put("men","Mende");
    languages.put("mga","Srednjoirski (900-1200)");
    languages.put("mic","Mikmak");
    languages.put("min","Mingangkabau");
    languages.put("mis","Ostali");
    languages.put("mkh","Mon-Khmer (ostali)");
    languages.put("mla","Malaga\u0161ki");
    languages.put("mlt","Malte\u0161ki");
    languages.put("mnc","Man\u010du");
    languages.put("mni","Manipuri");
    languages.put("mno","Manobo jezici");
    languages.put("moh","Mohawk");
    languages.put("mol","Moldavski");
    languages.put("mon","Mongolski");
    languages.put("mos","Mosi");
    languages.put("mul","vi\u0161ejezi\u010dni");
    languages.put("mun","Munda");
    languages.put("mus","Creek / Muskogee");
    languages.put("mwl","Mirandese");
    languages.put("mwr","Marvari");
    languages.put("myn","Maja jezici");
    languages.put("myv","Erzya");
    languages.put("nah","Nahuatl");
    languages.put("nai","Severnoameri\u010dki indijanski (ostali)");
    languages.put("nap","Napolitan");
    languages.put("nau","Nauru");
    languages.put("nav","Navaho");
    languages.put("nbl","Ndebele, ju\u017eni");
    languages.put("nde","Ndebele, severni");
    languages.put("ndo","Ndonga");
    languages.put("nds","Niskonema\u010dki / Niskosaksonski");
    languages.put("nep","Nepalski");
    languages.put("new","Newari / Nepal Bhasa");
    languages.put("nia","Nias");
    languages.put("nic","Nigersko-kordofanski (ostali)");
    languages.put("niu","Niuean");
    languages.put("nno","Norwegian Nynorsk");
    languages.put("nob","Norwegian Bokmal");
    languages.put("nog","Nogai");
    languages.put("non","Norse, Old");
    languages.put("nor","Norve\u0161ki");
    languages.put("nso","Severni Sotho / Pedi / Sepedi");
    languages.put("nub","Nubijski jezici");
    languages.put("nwc","Classical Newari / Old Newari / Classical Nepal Bhasa");
    languages.put("nya","Chichewa / Chewa / Nyanja");
    languages.put("nym","Nyamwezi");
    languages.put("nyn","Nyankole");
    languages.put("nyo","Nyoro");
    languages.put("nzi","Nzima");
    languages.put("oci","Occitan / Provansalski (posle 1500)");
    languages.put("oji","Ojibwa");
    languages.put("ori","Oriya");
    languages.put("orm","Oromo");
    languages.put("osa","Osage");
    languages.put("oss","Osetski");
    languages.put("ota","Otomanski turski (1500-1928)");
    languages.put("oto","Otomski jezici");
    languages.put("paa","Papuanski (ostali)");
    languages.put("pag","Pangasinan");
    languages.put("pal","Pahlavi");
    languages.put("pam","Pampanga");
    languages.put("pan","Panjabi / Punjabi");
    languages.put("pap","Papiamento");
    languages.put("pau","Palauan");
    languages.put("peo","Staropersijski (600pne-400ne)");
    languages.put("per","Persijski");
    languages.put("phi","Filipinski (ostali)");
    languages.put("phn","Feni\u010danski");
    languages.put("pli","Pali");
    languages.put("pol","Poljski");
    languages.put("pon","Pohnpeian");
    languages.put("por","Portugalski");
    languages.put("pra","Prakrit languages");
    languages.put("pro","Provansalski (do 1500)");
    languages.put("pus","Pushto");
    languages.put("que","Quechua");
    languages.put("raj","Rajasthani");
    languages.put("rap","Rapanui");
    languages.put("rar","Rarotongan");
    languages.put("roa","Romanski (ostali)");
    languages.put("roh","Retoromanski");
    languages.put("rom","Romski");
    languages.put("rsi","Rusinski");
    languages.put("rum","Rumunski");
    languages.put("run","Rundi");
    languages.put("rus","Ruski");
    languages.put("sad","Sandawe");
    languages.put("sag","Sango");
    languages.put("sah","Yakut");
    languages.put("sai","Ju\u017enoameri\u010dki indijanski (ostali)");
    languages.put("sal","Sali\u0161ki jezici");
    languages.put("sam","Samaritanski aramejski");
    languages.put("san","Sanskrt");
    languages.put("sas","Sasak");
    languages.put("sat","Santali");
    languages.put("scc","Srpski - \u0107irilica");
    languages.put("scn","Sicilijanski");
    languages.put("sco","\u0160kotski");
    languages.put("scr","Srpski - latinica");
    languages.put("sel","Selkupski");
    languages.put("sem","Semitski (ostali)");
    languages.put("sga","Irski, stari (do 900)");
    languages.put("sgn","Znakovni jezici");
    languages.put("shn","Shan");
    languages.put("sid","Sidamo");
    languages.put("sin","Sinhala");
    languages.put("sio","Siouan languages");
    languages.put("sit","Sino-Tibetan (other)");
    languages.put("sla","Slovenski (ostali)");
    languages.put("slo","Slova\u010dki");
    languages.put("slv","Slovena\u010dki");
    languages.put("sma","Southern Sami");
    languages.put("sme","Northern Sami");
    languages.put("smi","Sami languages (other)");
    languages.put("smj","Lule Sami");
    languages.put("smn","Inari Sami");
    languages.put("smo","Samoanski");
    languages.put("sms","Skolt Sami");
    languages.put("sna","Shona");
    languages.put("snd","Sindhi");
    languages.put("snk","Soninke");
    languages.put("sog","Sogdijski");
    languages.put("som","Somalijski");
    languages.put("son","Songhai");
    languages.put("sot","Sotho, Southern");
    languages.put("spa","\u0160panski / Kastiljanski");
    languages.put("srd","Sardinijski");
    languages.put("srr","Serer");
    languages.put("ssa","Nilsko-saharski (ostali)");
    languages.put("suk","Sukuma");
    languages.put("sun","Sundski");
    languages.put("sus","Susu");
    languages.put("sux","Sumerijanski");
    languages.put("swa","Svahili");
    languages.put("swe","\u0160vedski");
    languages.put("swz","Swazi");
    languages.put("syr","Sirijski");
    languages.put("tah","Tahitski");
    languages.put("tai","Tai (ostali)");
    languages.put("tam","Tamilski");
    languages.put("tat","Tatarski");
    languages.put("tel","Telugu");
    languages.put("tem","Timne");
    languages.put("ter","Tereno");
    languages.put("tet","Tetum");
    languages.put("tgk","Tad\u017eik");
    languages.put("tgl","Tagalog");
    languages.put("tha","Thai");
    languages.put("tib","Tibetanski");
    languages.put("tig","Tigre");
    languages.put("tir","Tigrinya");
    languages.put("tiv","Tiv");
    languages.put("tkl","Tokelau");
    languages.put("tlh","Klingon");
    languages.put("tli","Tlingit");
    languages.put("tmh","Tamashek");
    languages.put("tog","Tonga (Nyasa)");
    languages.put("ton","Tonga (Tonga Islands)");
    languages.put("tpi","Tok Pisin");
    languages.put("tsi","Cim\u0161ijen");
    languages.put("tsn","Tswana");
    languages.put("tso","Tsonga");
    languages.put("tuk","Turkmen");
    languages.put("tum","Tumbuka");
    languages.put("tup","Tupi jezici");
    languages.put("tur","Turski");
    languages.put("tut","Altajski (ostali)");
    languages.put("tvl","Tuvalu");
    languages.put("twi","Twi");
    languages.put("tyv","Tuvinian");
    languages.put("udm","Udmurt");
    languages.put("uga","Ugaritic");
    languages.put("uig","Uighur / Uyghur");
    languages.put("ukr","Ukrajinski");
    languages.put("umb","Umbundu");
    languages.put("und","neodre\u0111eni");
    languages.put("urd","Urdu");
    languages.put("uzb","Uzbe\u010dki");
    languages.put("vai","Vai");
    languages.put("ven","Venda");
    languages.put("vie","Vijetnamski");
    languages.put("vol","Volapuk");
    languages.put("vot","Votic");
    languages.put("wak","Vaka\u0161ki jezici");
    languages.put("wal","Walamo");
    languages.put("war","Waray");
    languages.put("was","Washo");
    languages.put("wel","Vel\u0161ki");
    languages.put("wen","Lu\u017ei\u010dkosrpski");
    languages.put("wln","Walloon");
    languages.put("wol","Volof");
    languages.put("xal","Kalmyk");
    languages.put("xho","Xhosa");
    languages.put("yao","Jao");
    languages.put("yap","Yapese");
    languages.put("yid","Jidi\u0161");
    languages.put("yor","Yoruba");
    languages.put("ypk","Yupik languages");
    languages.put("zap","Zapotec");
    languages.put("zen","Zenaga");
    languages.put("zha","Zhuang / Chuang");
    languages.put("znd","Zande");
    languages.put("zul","Zulu");
    languages.put("zun","Zuni");
  }
}
